### ISSUE TITLE
Failed to build DRILL-GTK and CLI  with DMD compiler

### ISSUE THREAD

**Issue by thebeast48** [yatima1460/Drill#82]
**Linux distro**
`OS: Manjaro Linux x86_64
Kernel: 6.1.1-1-MANJARO`
`DMD64 D Compiler v2.101.1`

**Build Version**
-trying to build GTK and CLI version

**Describe the bug**
after run the command to start building i end up with this error
`Error: linker exited with status 1
FAIL .dub/build/CLI-release-linux.posix-x86_64-dmd_v2.101.1-6C39C71395E3C3CF9DD4C449DC01380D5910DC1E4D6219E323C98332A9B6EA28/ drill-search-cli executable
Error /usr/bin/dmd failed with exit code 1.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: drill-search`

**Comment by yochananmarqos** [comment]
With DMD 2.102.1:

```
~/drill-search/src/Drill/src ~/drill-search/src/Drill
Using dub registry url 'https://code.dlang.org/'
Note: Failed to determine version of package drill-search at .. Assuming ~master.
Generating using build
Configuring dependent drill-search, deps:
Using custom build type 'release'.
    Starting Performing "release" build using /usr/bin/dmd for x86_64.
    Building drill-search ~master: building configuration [CLI]
[cwd=/build/drill-search/src/Drill/src] /usr/bin/dmd -J=. -m64 -L-zrelro -L-znow -c -of/build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o -release -inline -noboundscheck -O -w -version=Have_drill_search -version=StdLoggerDisableTrace -version=StdLoggerDisableInfo -version=StdLoggerDisableWarning -version=StdLoggerDisableError CLI/CLI.d Core/ApplicationInfo.d Core/Config.d Core/Context.d Core/Crawler.d Core/FileInfo.d Core/ListData.d Core/Meta.d Core/Utils.d -vcolumns
Core/Crawler.d(278,14): Deprecation: `Crawler.tryGetShallowFiles`: `in` contract may throw but function is marked as `nothrow`
     Linking drill-search-cli
[cwd=/build/drill-search/src/Drill/src] /usr/bin/dmd -of/build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o -L--no-as-needed -m64 -L-zrelro -L-znow
/usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o: in function `_D7Crawler14crawlDirectoryFS3std4file8DirEntryxASQv5regex8internal2ir__T5RegexTaZQjxQBlxAyaPPFxS8FileInfoQjPvZvxPvSQDj9container5dlist__T5DListTQEnZQlPFQEvxQCqZbPObZv':
Core/Utils.d:(.text._D7Crawler14crawlDirectoryFS3std4file8DirEntryxASQv5regex8internal2ir__T5RegexTaZQjxQBlxAyaPPFxS8FileInfoQjPvZvxPvSQDj9container5dlist__T5DListTQEnZQlPFQEvxQCqZbPObZv[_D7Crawler14crawlDirectoryFS3std4file8DirEntryxASQv5regex8internal2ir__T5RegexTaZQjxQBlxAyaPPFxS8FileInfoQjPvZvxPvSQDj9container5dlist__T5DListTQEnZQlPFQEvxQCqZbPObZv]+0x7ff): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
/usr/bin/ld: Core/Utils.d:(.text._D7Crawler14crawlDirectoryFS3std4file8DirEntryxASQv5regex8internal2ir__T5RegexTaZQjxQBlxAyaPPFxS8FileInfoQjPvZvxPvSQDj9container5dlist__T5DListTQEnZQlPFQEvxQCqZbPObZv[_D7Crawler14crawlDirectoryFS3std4file8DirEntryxASQv5regex8internal2ir__T5RegexTaZQjxQBlxAyaPPFxS8FileInfoQjPvZvxPvSQDj9container5dlist__T5DListTQEnZQlPFQEvxQCqZbPObZv]+0x8d2): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
/usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o: in function `_D3std4file__T12_DirIteratorVbi0ZQt6__ctorMFNcNeAyaEQByQBx8SpanModebZSQCqQCp__TQCnVbi0ZQCv':
Core/Utils.d:(.text._D3std4file__T12_DirIteratorVbi0ZQt6__ctorMFNcNeAyaEQByQBx8SpanModebZSQCqQCp__TQCnVbi0ZQCv[_D3std4file__T12_DirIteratorVbi0ZQt6__ctorMFNcNeAyaEQByQBx8SpanModebZSQCqQCp__TQCnVbi0ZQCv]+0x67): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
/usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o: in function `_D3std4file__T12_DirIteratorVbi0ZQt11__fieldDtorMFZv':
Core/Utils.d:(.text._D3std4file__T12_DirIteratorVbi0ZQt11__fieldDtorMFZv[_D3std4file__T12_DirIteratorVbi0ZQt11__fieldDtorMFZv]+0x11): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
/usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o: in function `_D3std4file__T12_DirIteratorVbi0ZQt8opAssignMFNcNjSQBxQBw__TQBuVbi0ZQCcZQw':
Core/Utils.d:(.text._D3std4file__T12_DirIteratorVbi0ZQt8opAssignMFNcNjSQBxQBw__TQBuVbi0ZQCcZQw[_D3std4file__T12_DirIteratorVbi0ZQt8opAssignMFNcNjSQBxQBw__TQBuVbi0ZQCcZQw]+0x2d): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
/usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o:Core/Utils.d:(.text._D3std9algorithm9iteration__T6filterS_DQBl4file__T10dirEntriesVbi0ZQrFAyaQdEQCwQBl8SpanModebZ1fMFNaNbNfSQDyQCn8DirEntryZbZ__TQDsTSQEyQDn__T12_DirIteratorVbi0ZQtZQFcMFQBlZSQGnQGmQGf__T12FilterResultS_DQHqQGf__TQGdVbi0ZQGlFQFvQFyQFwbZQFjMQFkTQEhZQCj[_D3std9algorithm9iteration__T6filterS_DQBl4file__T10dirEntriesVbi0ZQrFAyaQdEQCwQBl8SpanModebZ1fMFNaNbNfSQDyQCn8DirEntryZbZ__TQDsTSQEyQDn__T12_DirIteratorVbi0ZQtZQFcMFQBlZSQGnQGmQGf__T12FilterResultS_DQHqQGf__TQGdVbi0ZQGlFQFvQFyQFwbZQFjMQFkTQEhZQCj]+0xa9): more undefined references to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv' follow
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
FAIL /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5 drill-search-cli executable
Error /usr/bin/dmd failed with exit code 1.
```

It also fails to build with LDC 1.31.0:

```
~/drill-search/src/Drill/src ~/drill-search/src/Drill
Using dub registry url 'https://code.dlang.org/'
Note: Failed to determine version of package drill-search at .. Assuming ~master.
Generating using build
Configuring dependent drill-search, deps:
Using custom build type 'release'.
    Starting Performing "release" build using ldc2 for x86_64.
    Building drill-search ~master: building configuration [CLI]
ldc2 -J=. -march=x86-64 -L-zrelro -L-znow -c -of/build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/drill-search-cli.o -release -enable-inlining -Hkeep-all-bodies -boundscheck=off -O3 -w --oq -od=/build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/obj -d-version=Have_drill_search -d-version=StdLoggerDisableTrace -d-version=StdLoggerDisableInfo -d-version=StdLoggerDisableWarning -d-version=StdLoggerDisableError CLI/CLI.d Core/ApplicationInfo.d Core/Config.d Core/Context.d Core/Crawler.d Core/FileInfo.d Core/ListData.d Core/Meta.d Core/Utils.d -vcolumns
Core/Crawler.d(278,14): Deprecation: `Crawler.tryGetShallowFiles`: `in` contract may throw but function is marked as `nothrow`
     Linking drill-search-cli
ldc2 -of/build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/drill-search-cli /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/drill-search-cli.o -L--no-as-needed -march=x86-64 -L-zrelro -L-znow
/usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/drill-search-cli.o: in function `_D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya':
Utils.d:(.text._D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya+0x70): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
/usr/bin/ld: Utils.d:(.text._D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya+0x7a): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
/usr/bin/ld: Utils.d:(.text._D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya+0x192): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
/usr/bin/ld: Utils.d:(.text._D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya+0x1cc): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
/usr/bin/ld: Utils.d:(.text._D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya+0x1fb): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
/usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/drill-search-cli.o:Utils.d:(.text._D3std4file__T12_DirIteratorVbi0ZQt11__fieldDtorMFZv+0x1): more undefined references to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv' follow
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
FAIL /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E drill-search-cli executable
Error ldc2 failed with exit code 1.
```

**Comment by thebeast48** [comment]
where the problem come from

> With DMD 2.102.1:
> 
> ```
> ~/drill-search/src/Drill/src ~/drill-search/src/Drill
> Using dub registry url 'https://code.dlang.org/'
> Note: Failed to determine version of package drill-search at .. Assuming ~master.
> Generating using build
> Configuring dependent drill-search, deps:
> Using custom build type 'release'.
>     Starting Performing "release" build using /usr/bin/dmd for x86_64.
>     Building drill-search ~master: building configuration [CLI]
> [cwd=/build/drill-search/src/Drill/src] /usr/bin/dmd -J=. -m64 -L-zrelro -L-znow -c -of/build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o -release -inline -noboundscheck -O -w -version=Have_drill_search -version=StdLoggerDisableTrace -version=StdLoggerDisableInfo -version=StdLoggerDisableWarning -version=StdLoggerDisableError CLI/CLI.d Core/ApplicationInfo.d Core/Config.d Core/Context.d Core/Crawler.d Core/FileInfo.d Core/ListData.d Core/Meta.d Core/Utils.d -vcolumns
> Core/Crawler.d(278,14): Deprecation: `Crawler.tryGetShallowFiles`: `in` contract may throw but function is marked as `nothrow`
>      Linking drill-search-cli
> [cwd=/build/drill-search/src/Drill/src] /usr/bin/dmd -of/build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o -L--no-as-needed -m64 -L-zrelro -L-znow
> /usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o: in function `_D7Crawler14crawlDirectoryFS3std4file8DirEntryxASQv5regex8internal2ir__T5RegexTaZQjxQBlxAyaPPFxS8FileInfoQjPvZvxPvSQDj9container5dlist__T5DListTQEnZQlPFQEvxQCqZbPObZv':
> Core/Utils.d:(.text._D7Crawler14crawlDirectoryFS3std4file8DirEntryxASQv5regex8internal2ir__T5RegexTaZQjxQBlxAyaPPFxS8FileInfoQjPvZvxPvSQDj9container5dlist__T5DListTQEnZQlPFQEvxQCqZbPObZv[_D7Crawler14crawlDirectoryFS3std4file8DirEntryxASQv5regex8internal2ir__T5RegexTaZQjxQBlxAyaPPFxS8FileInfoQjPvZvxPvSQDj9container5dlist__T5DListTQEnZQlPFQEvxQCqZbPObZv]+0x7ff): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
> /usr/bin/ld: Core/Utils.d:(.text._D7Crawler14crawlDirectoryFS3std4file8DirEntryxASQv5regex8internal2ir__T5RegexTaZQjxQBlxAyaPPFxS8FileInfoQjPvZvxPvSQDj9container5dlist__T5DListTQEnZQlPFQEvxQCqZbPObZv[_D7Crawler14crawlDirectoryFS3std4file8DirEntryxASQv5regex8internal2ir__T5RegexTaZQjxQBlxAyaPPFxS8FileInfoQjPvZvxPvSQDj9container5dlist__T5DListTQEnZQlPFQEvxQCqZbPObZv]+0x8d2): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
> /usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o: in function `_D3std4file__T12_DirIteratorVbi0ZQt6__ctorMFNcNeAyaEQByQBx8SpanModebZSQCqQCp__TQCnVbi0ZQCv':
> Core/Utils.d:(.text._D3std4file__T12_DirIteratorVbi0ZQt6__ctorMFNcNeAyaEQByQBx8SpanModebZSQCqQCp__TQCnVbi0ZQCv[_D3std4file__T12_DirIteratorVbi0ZQt6__ctorMFNcNeAyaEQByQBx8SpanModebZSQCqQCp__TQCnVbi0ZQCv]+0x67): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
> /usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o: in function `_D3std4file__T12_DirIteratorVbi0ZQt11__fieldDtorMFZv':
> Core/Utils.d:(.text._D3std4file__T12_DirIteratorVbi0ZQt11__fieldDtorMFZv[_D3std4file__T12_DirIteratorVbi0ZQt11__fieldDtorMFZv]+0x11): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
> /usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o: in function `_D3std4file__T12_DirIteratorVbi0ZQt8opAssignMFNcNjSQBxQBw__TQBuVbi0ZQCcZQw':
> Core/Utils.d:(.text._D3std4file__T12_DirIteratorVbi0ZQt8opAssignMFNcNjSQBxQBw__TQBuVbi0ZQCcZQw[_D3std4file__T12_DirIteratorVbi0ZQt8opAssignMFNcNjSQBxQBw__TQBuVbi0ZQCcZQw]+0x2d): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
> /usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5/drill-search-cli.o:Core/Utils.d:(.text._D3std9algorithm9iteration__T6filterS_DQBl4file__T10dirEntriesVbi0ZQrFAyaQdEQCwQBl8SpanModebZ1fMFNaNbNfSQDyQCn8DirEntryZbZ__TQDsTSQEyQDn__T12_DirIteratorVbi0ZQtZQFcMFQBlZSQGnQGmQGf__T12FilterResultS_DQHqQGf__TQGdVbi0ZQGlFQFvQFyQFwbZQFjMQFkTQEhZQCj[_D3std9algorithm9iteration__T6filterS_DQBl4file__T10dirEntriesVbi0ZQrFAyaQdEQCwQBl8SpanModebZ1fMFNaNbNfSQDyQCn8DirEntryZbZ__TQDsTSQEyQDn__T12_DirIteratorVbi0ZQtZQFcMFQBlZSQGnQGmQGf__T12FilterResultS_DQHqQGf__TQGdVbi0ZQGlFQFvQFyQFwbZQFjMQFkTQEhZQCj]+0xa9): more undefined references to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv' follow
> collect2: error: ld returned 1 exit status
> Error: linker exited with status 1
> FAIL /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-dmd_v2.102.1-4C29FC23FE0FE3C549462265689F43BFA2E441BD9D8A5C573F952E0A3B6800B5 drill-search-cli executable
> Error /usr/bin/dmd failed with exit code 1.
> ```
> 
> It also fails to build with LDC 1.31.0:
> 
> ```
> ~/drill-search/src/Drill/src ~/drill-search/src/Drill
> Using dub registry url 'https://code.dlang.org/'
> Note: Failed to determine version of package drill-search at .. Assuming ~master.
> Generating using build
> Configuring dependent drill-search, deps:
> Using custom build type 'release'.
>     Starting Performing "release" build using ldc2 for x86_64.
>     Building drill-search ~master: building configuration [CLI]
> ldc2 -J=. -march=x86-64 -L-zrelro -L-znow -c -of/build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/drill-search-cli.o -release -enable-inlining -Hkeep-all-bodies -boundscheck=off -O3 -w --oq -od=/build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/obj -d-version=Have_drill_search -d-version=StdLoggerDisableTrace -d-version=StdLoggerDisableInfo -d-version=StdLoggerDisableWarning -d-version=StdLoggerDisableError CLI/CLI.d Core/ApplicationInfo.d Core/Config.d Core/Context.d Core/Crawler.d Core/FileInfo.d Core/ListData.d Core/Meta.d Core/Utils.d -vcolumns
> Core/Crawler.d(278,14): Deprecation: `Crawler.tryGetShallowFiles`: `in` contract may throw but function is marked as `nothrow`
>      Linking drill-search-cli
> ldc2 -of/build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/drill-search-cli /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/drill-search-cli.o -L--no-as-needed -march=x86-64 -L-zrelro -L-znow
> /usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/drill-search-cli.o: in function `_D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya':
> Utils.d:(.text._D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya+0x70): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
> /usr/bin/ld: Utils.d:(.text._D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya+0x7a): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
> /usr/bin/ld: Utils.d:(.text._D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya+0x192): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
> /usr/bin/ld: Utils.d:(.text._D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya+0x1cc): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
> /usr/bin/ld: Utils.d:(.text._D5Utils28mergeAllTextFilesInDirectoryFyAaZAAya+0x1fb): undefined reference to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv'
> /usr/bin/ld: /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E/drill-search-cli.o:Utils.d:(.text._D3std4file__T12_DirIteratorVbi0ZQt11__fieldDtorMFZv+0x1): more undefined references to `_D3std8typecons__T14SafeRefCountedTSQBi4file15DirIteratorImplVEQCjQCi24RefCountedAutoInitializei0ZQDc6__dtorMFZv' follow
> collect2: error: ld returned 1 exit status
> Error: /usr/bin/cc failed with status: 1
> FAIL /build/.dub/cache/drill-search/~master/build/CLI-release-linux.posix-x86_64-ldc_v1.31.0-5E55A974058BDBCD6D376A25D158147DE1290E4C479F50B3144E218E78F06E6E drill-search-cli executable
> Error ldc2 failed with exit code 1.
> `

**Comment by yochananmarqos** [comment]
@thebeast48 All you did was quote my logs. Where does the problem come from? :thinking:

**Comment by thebeast48** [comment]
i was trying to build the last version of drill using dmd and via aur and i face the same problem 

but using the compiled binary in repo work well

**Comment by yochananmarqos** [comment]
@thebeast48 That's nice. What does commenting, _where the problem come from_ and quoting my logs accomplish?

Did you mean, _Where **does** the problem come from?_ Notice the added word  you missed and proper punctuation to express it as a question.

**Comment by thebeast48** [comment]
sorry bro but English not my native language

**Comment by yatima1460** [comment]
closing because moving to dotnet7
