### ISSUE TITLE
Error: function Utils._getMountpoints has no return statement

### ISSUE THREAD

**Issue by probonopd** [yatima1460/Drill#72]
**Operating system**

FreeBSD 12.1-RELEASE r354233 GENERIC

**Build Version**

Latest from git

**Describe the bug**

```
(dmd-2.095.0)[root@box /tmp/Drill]# echo 0 > DRILL_VERSION
(dmd-2.095.0)[root@box /tmp/Drill]# dub build -b release -c CLI
Performing "release" build using /root/dlang/dmd-2.095.0/freebsd/bin64/dmd for x86_64.
drill-search ~master: building configuration "CLI"...
Core/Utils.d(60,10): Error: function Utils._getMountpoints has no return statement, but is expected to return a value of type string[]
/root/dlang/dmd-2.095.0/freebsd/bin64/dmd failed with exit code 1.
```
