### ISSUE TITLE
Error: file "DRILL_VERSION" cannot be found

### ISSUE THREAD

**Issue by probonopd** [yatima1460/Drill#71]
Trying to compile on FreeBSD but getting `Error: file "DRILL_VERSION" cannot be found`:

```
% uname -v
FreeBSD 12.1-RELEASE r354233 GENERIC

% curl -fsS https://dlang.org/install.sh | bash -s dmd

% source ~/dlang/dmd-2.095.0/activate

% git clone https://github.com/yatima1460/Drill

% cd Drill

% dub build -b release -c CLI                         
Performing "release" build using /usr/home/user/dlang/dmd-2.095.0/freebsd/bin64/dmd for x86_64.
drill-search ~master: building configuration "CLI"...
Core/Meta.d(15,29): Error: file "DRILL_VERSION" cannot be found or not in a path specified with -J
Core/Meta.d(15,29):        Path(s) searched (as provided by -J):
Core/Meta.d(15,29):        [0]: .
/usr/home/user/dlang/dmd-2.095.0/freebsd/bin64/dmd failed with exit code 1.
```

**Comment by probonopd** [comment]
Workaround for building locally:
`echo 0 > DRILL_VERSION`

**Comment by yochananmarqos** [comment]
I tried passing `DRILL_VERSION=566` to the `dub build` command, but it didn't like that:

```
Note: Failed to determine version of package drill-search at .. Assuming ~master.
Invalid SemVer format: 566
```

Creating the `DRILL_VERSION` file allows it to build, but it still doesn't like it:

```
Note: Failed to determine version of package drill-search at .. Assuming ~master.
```

Both the CLI and GUI report the correct version, so I guess it doesn't make any difference.

**Comment by yatima1460** [comment]
@probonopd updated everything and made it a rolling release, so closing this issue; and would be nice to add a simpler AppImage creation too
